username = input('Введите имя: ')
title = input('Введите заголовок: ')
content = input('Введите Описание: ')
status = input('Статус: ')
created_date = input ('Введите дату создания (день-месяц-год): ')
issue_date = input ('Введите дату истечения (день-месяц-год): ')
print ("Имя пользователя:",username)
print ("Заголовок заметки:",title)
print ("Описание заметки:",content)
print ("Статус заметки:",status)
print ("Дата создания заметки:",created_date)
print ("Дата истечения заметки:",issue_date)